### ISSUE TITLE
ERROR: rejecting unrequested file-list name: categoryVotes.csv

### ISSUE THREAD

**Issue by TheBinaryLoop** [mchangrh/sb-mirror#24]
Uses SponsorBlock data from https://sponsor.ajay.app/
Downloading from mirror: sponsorblock.kavin.rocks
receiving incremental file list
ERROR: rejecting unrequested file-list name: categoryVotes.csv
rsync error: protocol incompatibility (code 2) at flist.c(998) [Receiver=3.2.4]
Starting rsync daemon
Downloading from mirror: sponsorblock.kavin.rocks
receiving incremental file list
ERROR: rejecting unrequested file-list name: categoryVotes.csv
rsync error: protocol incompatibility (code 2) at flist.c(998) [Receiver=3.2.4]

Can anybody help me?

**Comment by mchangrh** [comment]
this was due to a version incompatibility, it was rebuilt to match the version that kavin uses

**Comment by TheBinaryLoop** [comment]
What do I need to do now? Do I need to update anything?

**Comment by mchangrh** [comment]
pull the latest version and it should work fine with that mirorr

**Comment by mkody** [comment]
Well right now all 5-minutes delayed mirrors (except sb.ltn.fi) are returning an HTML page.  
I had the same issue with `protocol incompatibility` with the other mirrors fyi. Running rsync directly on my machine to retrieve the .csv worked instead.

**Comment by mchangrh** [comment]
The most recently tagged images was 5 hours ago with 0 downloads, so it sounds like you are using an older version.

Only `sponsorblock.kavin.rocks` should have the version incompatibility, mirror.sb.mchang.xyz is stuck on 3.2.3. 

upstream is returning an html file, which means downstream follows. I'll roll back to a good version and disable auto-updates

**Comment by mkody** [comment]
> The most recently tagged images was 5 hours ago with 0 downloads, so it sounds like you are using an older version.

Well that's weird, https://hub.docker.com/r/mchangrh/sb-mirror/tags says "2 days ago" for bother the :latest and :alpine tags.

**Comment by mchangrh** [comment]
I bet they invalidated my tokens again, ugh

**Comment by mchangrh** [comment]
pushed, newest tags should be up-to-date

mirrors reverted to a manual backup

**Comment by mkody** [comment]
Thanks! Can confirm it works now
