### ISSUE TITLE
Links in readme are broken.

### ISSUE THREAD

**Issue by ballsystemlord** [mchangrh/sb-mirror#33]
archive.sb.mchang.xyz
mirror.sb.mchang.xyz
sponsorblock.kavin.rocks

Just time out when I'm trying to access them. I'm assuming that these mirror sites are down.
I suggest that the readme be updated with either new links or some other option for sync-ing.

Thanks!

**Comment by mchangrh** [comment]
Both of mine were taken down due to abuse, I'm guessing kavin is not keeping theirs up either. Will remove.

**Comment by ballsystemlord** [comment]
I'm sorry to hear that. I hope we'll have some nice mirror sites in the future.
